name: 'Delete workflow runs'
description: 'An action to delete workflow runs in a repository.'
author: 'Mattraks'

inputs:
  token:
    description: 'The token used to authenticate.'
    required: true
    default: ${{ github.token }}

  baseUrl:
    description: 'The base api url to be used in enterprise github instances'
    required: false
    default: "https://api.github.com"
  repository:
    description: 'The name of the repository.'
    required: true
    default: ${{ github.repository }}

  retain_days:
    description: 'The number of days.'
    required: true
    default: 30

  keep_minimum_runs:
    description: 'The minimum runs to keep for each workflow.'
    required: true
    default: 6

  delete_workflow_pattern:
    description: 'The name or filename of the workflow. if not set then it will target all workflows.'
    required: false

  delete_workflow_by_state_pattern:
    description: 'Remove workflow by state: active, deleted, disabled_fork, disabled_inactivity, disabled_manually'
    required: false

  delete_run_by_conclusion_pattern:
    description: 'Remove workflow by conclusion: action_required, cancelled, failure, skipped, success'
    required: false

  dry_run:
    description: 'Only log actions, do not perform any delete operations'
    required: false


runs:
  using: 'node16'
  main: 'dist/index.js'

branding:
  icon: 'delete'
  color: 'red'
